language: android
sudo: false
install: true
script:
    - cd submodules/soomla-android-core
    - ./download_deps
    - ant -buildfile soomla-android-core.xml -Dsoomla.filename="SoomlaAndroidCore" all
    - cd ../../SoomlaAndroidProfile
    - ant -buildfile android-profile.xml -Dsoomla.filename="AndroidProfile" all
